-- Database Dump for Pucuk Pena (Railway & Production)
-- Generated: 2026-09-07 02:04:57

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `admin_users`;
CREATE TABLE `admin_users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `admin_users` (`id`, `username`, `password`, `created_at`) VALUES
('1', 'admin', '$2y$10$LhwMOm5jsEAj8mr16B8Gt.doNz5VRretQg.jzC7S9wceyIHh3quU6', '2026-09-07 07:35:01');

DROP TABLE IF EXISTS `articles`;
CREATE TABLE `articles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `type` varchar(100) NOT NULL DEFAULT 'Berita Utama',
  `cat` varchar(50) NOT NULL DEFAULT 'berita',
  `badge` varchar(50) NOT NULL DEFAULT 'berita',
  `title` varchar(500) NOT NULL,
  `excerpt` text,
  `content` longtext,
  `author` varchar(200) DEFAULT NULL,
  `date_display` varchar(100) DEFAULT NULL,
  `views` varchar(20) DEFAULT '0',
  `img` text,
  `tags` varchar(500) DEFAULT '[]',
  `status` enum('draft','published') DEFAULT 'published',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=104 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `articles` (`id`, `type`, `cat`, `badge`, `title`, `excerpt`, `content`, `author`, `date_display`, `views`, `img`, `tags`, `status`, `created_at`, `updated_at`) VALUES
('1', 'Berita Utama', 'berita', 'berita', 'Pemerintah Luncurkan Program Revitalisasi 100 Desa Wisata di Seluruh Nusantara', 'Program senilai Rp2,5 triliun diharapkan meningkatkan ekonomi kerakyatan dan menyerap 50 ribu tenaga kerja baru di sektor pariwisata.', 'Jakarta — Pemerintah melalui Kementerian Pariwisata dan Ekonomi Kreatif resmi meluncurkan program Revitalisasi 100 Desa Wisata yang menargetkan peningkatan infrastruktur, pelatihan SDM, dan promosi digital di desa-desa potensial.\n\nMenteri menyatakan program ini merupakan bagian dari visi Indonesia Emas 2045, di mana sektor pariwisata diharapkan menyumbang 12 persen terhadap PDB nasional.\n\n\"Kita tidak hanya membangun jalan dan homestay, tapi juga ekosistem digital agar desa-desa ini bisa dikenal dunia,\" ujarnya dalam konferensi pers di Jakarta, Jumat (28/6).\n\nProgram akan dimulai di 20 provinsi prioritas termasuk Bali, Yogyakarta, NTT, dan Sulawesi Selatan.', 'Rina Wijaya', '28 Juni 2025', '45.2K', 'img/desa_wisata.png', '[\"Pariwisata\",\"Pemerintah\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('2', 'Berita Utama', 'berita', 'berita', 'G20 Sepakat Perkuat Kerjasama Transisi Energi Hijau Global', 'Para pemimpin negara G20 menyepakati deklarasi bersama untuk mengalokasikan USD 100 miliar guna akselerasi energi terbarukan.', 'Roma — KTT G20 yang digelar di Italia menghasilkan deklarasi bersejarah tentang transisi energi hijau. Para pemimpin dunia sepakat meningkatkan investasi energi terbarukan dan mengurangi ketergantungan bahan bakar fosil.\n\nIndonesia menjadi salah satu negara yang mendapat apresiasi atas komitmen menutup PLTU batu bara secara bertahap dan mengembangkan energi geothermal serta surya.', 'Ahmad Rizki', '27 Juni 2025', '38.7K', 'img/g20_summit.png', '[\"Internasional\",\"Lingkungan\",\"G20\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('3', 'Berita Utama', 'berita', 'berita', 'Rupiah Menguat ke Rp15.820 per Dolar AS, BI Optimis Stabil', 'Bank Indonesia mencatat aliran masuk investasi portofolio asing sebesar USD 1,2 miliar dalam sepekan terakhir.', 'Jakarta — Rupiah menguat 0,3 persen pada perdagangan Kamis kemarin, didorong oleh sentimen positif pasar global dan kebijakan moneter BI yang dianggap hawkish.\n\nDeputi Gubernur BI menyatakan cadangan devisa tetap aman di level USD 148 miliar, cukup untuk 6,2 bulan impor.', 'Dian Pratiwi', '27 Juni 2025', '29.1K', 'img/rupiah_exchange.png', '[\"Rupiah\",\"BI\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('4', 'Berita Utama', 'berita', 'berita', 'Startup AI Indonesia Raih Pendanaan Series B Senilai USD 80 Juta', 'NeuralNusantara dikembangkan untuk solusi AI berbahasa Indonesia yang melayani 700 bahasa daerah.', 'Bandung — Startup kecerdasan buatan asal Bandung, NeuralNusantara, berhasil meraih pendanaan Series B dari investor global termasuk Sequoia Capital India dan Alpha JWC Ventures.\n\nCEO startup ini menyebut produk mereka sudah digunakan 200 perusahaan enterprise di Indonesia dan ASEAN.', 'Fajar Nugroho', '26 Juni 2025', '52.4K', 'img/ai_startup.png', '[\"Startup\",\"AI\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('5', 'Berita Utama', 'berita', 'berita', 'Timnas Indonesia Lolos ke Piala Asia 2027 Setelah Dramatis di Kualifikasi', 'Gol injury time Evan Dimas memastikan kemenangan 2-1 atas Bahrain dan tiket ke Qatar.', 'Surabaya — Stadion Gelora Bung Tomo bergemuruh. Timnas Indonesia menorehkan sejarah dengan lolos ke Piala Asia 2027 setelah mengalahkan Bahrain 2-1.\n\nPelatih Shin Tae-yong memuji mental juara para pemain yang bermain total meski dalam tekanan.', 'Bambang Sutrisno', '26 Juni 2025', '89.3K', 'img/timnas_football.png', '[\"Timnas\",\"Sepak Bola\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('6', 'Opini', 'opini', 'opini', 'Demokrasi Digital: Antara Kebebasan Berekspresi dan Misinformasi', 'Media sosial telah mengubah landscape demokrasi, tapi tantangan hoaks dan echo chamber semakin mengkhawatirkan.', 'Opini — Kita hidup di era di mana setiap warga negara bisa menjadi produsen informasi. Namun kemudahan ini membawa konsekuensi: misinformasi menyebar 6 kali lebih cepat dibanding fakta.\n\nPemerintah perlu regulasi yang tepat, bukan sensor, melainkan literasi digital masif. Media mainstream juga harus beradaptasi dengan kecepatan digital tanpa mengorbankan verifikasi.\n\nDemokrasi digital bukan ancaman — jika kita mampu mengelolanya dengan bijak.', 'Prof. Dr. Maya Sari', '25 Juni 2025', '18.6K', 'img/demokrasi_digital.png', '[\"Demokrasi\",\"Media\",\"Opini\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('7', 'Pendidikan', 'pendidikan', 'pendidikan', 'Pendidikan Merdeka Belajar: Dua Tahun Later, Apa Hasilnya?', 'Evaluasi kritis terhadap kebijakan Merdeka Belajar dan rekomendasi perbaikan untuk era berikutnya.', 'Refleksi kebijakan pendidikan nasional menunjukkan progress di beberapa aspek, terutama fleksibilitas kurikulum. Namun kesenjangan infrastruktur digital antar daerah masih menjadi pekerjaan rumah besar.\n\nGuru-guru hebat ada di mana-mana, tapi sistem penghargaan dan pengembangan profesional mereka masih perlu diperbaiki.', 'Dr. Hendra Wijaya', '24 Juni 2025', '14.2K', 'img/pendidikan_sekolah.png', '[\"Pendidikan\",\"Kebijakan\",\"Opini\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('8', 'Essay', 'essay', 'essay', 'Langit Senja di Kampung Halaman: Ode untuk yang Telah Pergi', 'Essay tentang nostalgia, kehilangan, dan makna pulang ke akar budaya di tengah modernitas yang menggerus.', 'Essay — Ada sesuatu yang magis tentang senja di desa. Jemputan angin padi, suara azan yang bersahutan, dan aroma ibu yang sedang menumis rempah di dapur.\n\nSaya pulang setelah lima belas tahun merantau. Jalan setapak yang dulu saya lalui dengan sepatu bolong kini sudah diaspal. Warung Pak Temon sudah diganti minimarket. Tapi langit senjanya — langit senja tetap sama.\n\nDalam essay ini, saya mencoba merangkum perasaan yang sulit diucapkan: bahwa pulang bukan tentang tempat, melainkan tentang siapa kita setelah pergi dan kembali.', 'Saraswati Dewi', '23 Juni 2025', '22.8K', 'img/senja_desa.png', '[\"Essay\",\"Sastra\",\"Nostalgia\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('9', 'Essay', 'essay', 'essay', 'Catatan dari Garis Khatulistiwa: Iklim, Identitas, dan Masa Depan', 'Perjalanan literer melintasi Indonesia equatorial dan refleksi tentang krisis iklim yang personal.', 'Membaca perubahan iklim dari buku teks berbeda dengan merasakannya di tubuh sendiri. Di Palangkaraya, kabut asap bukan lagi musiman — ia tinggal.\n\nEssay ini adalah catatan perjalanan dan pergulatan batin tentang apa artinya menjadi generasi yang mewarisi bumi yang sedang sakit.', 'Agus Prasetyo', '22 Juni 2025', '16.4K', 'img/senja_desa.png', '[\"Essay\",\"Iklim\",\"Lingkungan\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('10', 'Hikmah', 'hikmah', 'hikmah', 'Sejarah Tersembunyi: Jejak Perdagangan Rempah di Maluku', 'Artikel mendalam tentang bagaimana cengkeh dan pala membentuk geopolitik dunia selama empat abad.', 'Maluku pernah menjadi pusat dunia. Cengkeh dan pala yang tumbuh hanya di sana membuat bangsa-bangsa Eropa berlayar ribuan mil, berperang, dan berkoloni.\n\nArtikel ini menelusuri jejak-jejak sejarah yang masih bisa ditemukan di Ternate, Tidore, dan Banda — dari benteng VOC hingga kompleks istana Kesultanan.', 'Historian Team', '21 Juni 2025', '31.5K', 'img/desa_wisata.png', '[\"Sejarah\",\"Maluku\",\"Budaya\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('11', 'Pendidikan', 'pendidikan', 'pendidikan', 'Psikologi Generasi Z: Memahami Coquette, Delulu, dan Fenomena Digital', 'Analisis sosial-budaya tentang tren kekinian dan dampaknya terhadap kesehatan mental remaja.', 'Setiap generasi memiliki kode bahasanya sendiri. Generasi Z, lahir di era digital native, menciptakan kosakata dan identitas yang membingungkan generasi sebelumnya.\n\nArtikel ini mengupas fenomena-fenomena pop culture digital dengan pendekatan psikologi dan antropologi digital.', 'Dr. Lestari Nugraha', '20 Juni 2025', '44.1K', 'img/demokrasi_digital.png', '[\"Gen-Z\",\"Psikologi\",\"Artikel\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('12', 'Berita Utama', 'berita', 'investigasi', '[INVESTIGASI] Jejak Korupsi Proyek Jalan Tol Trans-Pulau: Apa yang Terlewat?', 'Tim investigasi Pucuk Pena menelusuri aliran dana proyek tol senilai Rp12 triliun yang mangkrak selama tiga tahun.', 'Investigasi — Dokumen yang kami peroleh menunjukkan indikasi mark-up biaya konstruksi hingga 40 persen. Empat perusahaan konstruksi terafiliasi dengan pejabat daerah tercatat sebagai penerima tender.\n\nKPK telah menerima laporan dan memulai audit internal. Artikel ini adalah bagian pertama dari seri tiga laporan investigasi.', 'Tim Investigasi Pucuk Pena', '19 Juni 2025', '67.9K', 'img/maraton_borobudur.png', '[\"Investigasi\",\"Korupsi\",\"Nasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('13', 'Berita Utama', 'berita', 'berita', 'Indonesia Luncurkan Satelit Nusantara-3 untuk Akses Internet 3T', 'Satelit HTS generasi terbaru mampu melayani 150 Mbps per terminal di daerah terpencil.', 'Sorong — Satelit Nusantara-3 berhasil diluncurkan dari Cape Canaveral dan akan mulai beroperasi penuh November 2025.\n\nMenteri Kominfo menyebut ini langkah strategis untuk menutup digital divide di 12.500 desa yang belum terjangkau fiber optik.', 'Tech Desk', '18 Juni 2025', '41.3K', 'img/iot_polusi_air.png', '[\"Satelit\",\"Teknologi\",\"Digital\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('14', 'Opini', 'opini', 'opini', 'UMKM Go Digital: Peluang atau Jebakan Platform?', 'Refleksi tentang ketergantungan UMKM pada marketplace dan strategi membangun brand mandiri.', 'Digitalisasi UMKM bukan lagi pilihan, melainkan keharusan. Tapi ketergantungan pada platform e-commerce dengan komisi 15-25 persen menggerus margin tipis pelaku usaha kecil.\n\nSaya berargumen: UMKM perlu strategi omnichannel dengan website sendiri sebagai home base.', 'Ratna Kartika, SE', '17 Juni 2025', '12.7K', 'img/desa_wisata.png', '[\"UMKM\",\"Digital\",\"Opini\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('15', 'Berita Utama', 'berita', 'berita', 'WHO Umumkan Endemi COVID-19 Resmi Berakhir di Seluruh Dunia', 'Deklarasi bersejarah setelah lebih dari lima tahun pandemi global melanda umat manusia.', 'Jenewa — WHO secara resmi mencabut status pandemi COVID-19 dan mengumumkan fase endemi global. Direktur Jenderal WHO menyatakan vaksinasi global mencapai 78 persen populasi dewasa.\n\nIndonesia tercatat sebagai salah satu negara dengan program vaksinasi tercepat di ASEAN.', 'Global Desk', '16 Juni 2025', '55.6K', 'img/g20_summit.png', '[\"WHO\",\"Kesehatan\",\"Internasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('16', 'Hikmah', 'hikmah', 'hikmah', 'Arsitektur Vernakular Nusantara: Kearifan Lokal yang Relevan di Era Modern', 'Mengapa rumah panggung, joglo, dan rumah gadang memiliki prinsip desain yang lebih sustainable.', 'Sebelum istilah \"green building\" populer, nenek moyang kita sudah membangun dengan prinsip sustainable. Ventilasi silang, material lokal, dan orientasi matahari — semua sudah ada dalam arsitektur tradisional Indonesia.\n\nArtikel ini mengajak profesional dan masyarakat untuk kembali belajar dari kearifan lokal.', 'Ir. Budi Santoso', '15 Juni 2025', '19.8K', 'img/rupiah_exchange.png', '[\"Arsitektur\",\"Budaya\",\"Artikel\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('17', 'Opini', 'opini', 'opini', 'Kecerdasan Buatan dan Arah Baru Jurnalisme Indonesia', 'Apakah AI akan menggantikan jurnalis atau justru memperkuat integritas informasi? Analisis kritis masa depan media.', 'Jakarta — Perkembangan Kecerdasan Buatan (AI) telah memicu perdebatan sengit di dunia jurnalistik. Di satu sisi, AI menawarkan efisiensi tinggi dalam analisis data besar dan penulisan laporan rutin. Di sisi lain, kekhawatiran akan bias algoritma, hilangnya sentuhan kemanusiaan, dan hoaks yang dihasilkan AI semakin meningkat.\n\nDalam wawancara kami dengan pengamat media, ia menyarankan agar jurnalis memanfaatkan AI sebagai asisten riset, bukan pengganti verifikasi jurnalisme.\n\n\"AI tidak memiliki etika dan empati. Dua hal itulah inti dari jurnalisme berkualitas,\" tegasnya.\n\nRedaksi Pucuk Pena berkomitmen untuk selalu mengedepankan etika jurnalisme manusiawi dalam setiap pemberitaan.', 'Dr. Irfan Hakim', '14 Juni 2025', '22.4K', 'img/ai_startup.png', '[\"AI\",\"Jurnalisme\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('18', 'Essay', 'essay', 'essay', 'Secangkir Kopi Gayo: Rasa, Aroma, dan Narasi Perjuangan Petani', 'Esai mendalam tentang kehidupan petani kopi di dataran tinggi Gayo dan bagaimana secangkir kopi bercerita tentang sejarah lokal.', 'Aceh — Di dataran tinggi Gayo, kopi bukan sekadar komoditas dagang, melainkan napas kehidupan dan sejarah perlawanan. Sejak era kolonial Belanda, varietas kopi Arabika Gayo telah mengharumkan nusantara hingga pasar Eropa.\n\nNamun di balik aromanya yang harum dan rasanya yang kaya dengan keasaman seimbang, tersimpan pergulatan para petani lokal dalam menghadapi fluktuasi harga global dan tantangan perubahan iklim.\n\n\"Tahun ini curah hujan tidak menentu. Bunganya gugur sebelum jadi buah,\" keluh Pak Hamdan, seorang petani kopi di Bener Meriah.\n\nEsai ini menelusuri bagaimana kopi merekatkan ikatan sosial masyarakat Gayo melalui tradisi minum kopi bersama di kedai-kedai lokal (kopi luwak) yang kini bertransformasi menjadi ruang diskusi publik.', 'Arian Ramadhan', '13 Juni 2025', '18.5K', 'img/timnas_football.png', '[\"Kopi\",\"Gayo\",\"Esai\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('19', 'Berita Utama', 'berita', 'berita', 'Revolusi Genomik: Membaca Cetak Biru Manusia Indonesia', 'Bagaimana proyek pemetaan genom nasional membantu mendeteksi penyakit langka dan menciptakan pengobatan personal.', 'Sains — Kementerian Kesehatan baru-baru ini meluncurkan program pemetaan genom skala nasional. Program ini bertujuan mengidentifikasi struktur genetik spesifik dari berbagai populasi etnis di Indonesia guna mendukung pengobatan presisi.\n\nIlmuwan menjelaskan bahwa obat-obatan konvensional seringkali dibuat berdasarkan studi populasi barat, sehingga efektivitasnya bisa berbeda pada genetik orang Indonesia.\n\n\"Dengan memetakan genom lokal, kita bisa merancang terapi kanker dan obat diabetes yang 100% cocok dengan profil genetik pasien,\" ungkap kepala peneliti.\n\nHasil awal menunjukkan keunikan variasi genetik yang dapat membantu mendeteksi risiko penyakit turunan sejak usia dini.', 'Prof. Dr. Widya Astuti', '12 Juni 2025', '34.7K', 'img/demokrasi_digital.png', '[\"Sains\",\"Genom\",\"Kesehatan\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('20', 'Berita Utama', 'berita', 'berita', 'DPR Resmi Sahkan RUU Perlindungan Konsumen Transaksi Digital', 'Undang-undang baru mengatur hak refund, pembatasan penyebaran data pribadi oleh e-commerce, dan denda berat bagi penipu online.', 'Jakarta — Dewan Perwakilan Rakyat (DPR) RI akhirnya mengesahkan Rancangan Undang-Undang Perlindungan Konsumen Digital. Regulasi ini dirancang untuk melindungi hak-hak konsumen dalam transaksi e-commerce, tekfin (fintech), dan media sosial.\n\nSalah satu pasal krusial adalah kewajiban platform belanja online menyediakan fitur refund cepat jika barang tidak sesuai deskripsi, serta denda hingga Rp10 Miliar bagi platform yang terbukti membocorkan data pribadi pengguna.\n\n\"Ini adalah kemenangan bagi jutaan pengguna internet di Indonesia,\" ujar perwakilan asosiasi e-commerce.\n\nUndang-undang ini akan mulai diberlakukan secara penuh mulai awal tahun depan.', 'Indra Jaya', '11 Juni 2025', '41.9K', 'img/pendidikan_sekolah.png', '[\"DPR\",\"Hukum\",\"Digital\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('21', 'Berita Utama', 'berita', 'investigasi', 'Gempa Magnitudo 5.2 Guncang Maluku Tenggara, Redaksi Pantau Kondisi Korban', 'Badan Meteorologi Klimatologi dan Geofisika menyatakan gempa tidak berpotensi tsunami namun warga dihimbau waspada gempa susulan.', 'Maluku — Gempa berkekuatan Magnitudo 5.2 mengguncang wilayah Maluku Tenggara pada pagi hari. Berdasarkan laporan BMKG, pusat gempa berada di kedalaman 10 kilometer di bawah laut, sekitar 45 km barat laut pulau Tual.\n\nBMKG mengonfirmasi bahwa gempa tersebut tidak berpotensi memicu gelombang tsunami. Namun, warga di sepanjang pesisir dihimbau agar tetap waspada akan adanya gempa susulan.\n\n\"Getarannya terasa cukup kuat selama 5 detik. Beberapa warga sempat lari keluar rumah,\" ujar koresponden Pucuk Pena di lokasi.\n\nBelum ada laporan mengenai kerusakan bangunan parah atau korban jiwa.', 'Pucuk Pena Maluku', '10 Juni 2025', '56.2K', 'img/senja_desa.png', '[\"Gempa\",\"Maluku\",\"BMKG\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('22', 'Opini', 'opini', 'opini', 'Krisis Eksistensial Generasi Z di Tengah Dominasi Algoritma Media Sosial', 'Mengapa scrolling tiada akhir merusak rentang perhatian anak muda dan bagaimana kita bisa merebut kembali kesadaran kita.', 'Opini — Menghabiskan waktu 5-6 jam sehari untuk menggulirkan layar (scrolling) media sosial telah menjadi norma bagi mayoritas Generasi Z. Algoritma platform yang dirancang untuk menjaga perhatian pengguna telah menciptakan ruang gema (echo chamber) yang memperkuat kecemasan sosial dan krisis eksistensial.\n\nPsikolog klinis berpendapat bahwa paparan terus-menerus terhadap kehidupan orang lain yang \"sempurna\" di layar memicu sindrom FOMO (Fear Of Missing Out).\n\n\"Kita kehilangan kemampuan untuk melamun dan memikirkan hal-hal mendalam karena otak kita terus disuplai dopamin instan,\" jelasnya.\n\nLangkah kecil seperti detoks digital 24 jam seminggu bisa menjadi awal yang baik untuk merebut kembali kontrol mental kita.', 'Nadia Utami, M.Psi', '9 Juni 2025', '28.9K', 'img/anggrek_ungu.png', '[\"Gen-Z\",\"Mental\",\"Media\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('23', 'Hikmah', 'hikmah', 'hikmah', 'Nostalgia Kota Lama Semarang: Menolak Lupa di Balik Dinding Lapuk', 'Catatan perjalanan menyusuri gang-gang sunyi Kota Lama Semarang yang sarat akan warisan kolonial dan refleksi modernitas.', 'Semarang — Menyusuri jalanan paving Kota Lama Semarang seperti melintasi mesin waktu. Dinding-dinding bata merah yang terkelupas, jendela kayu jati raksasa, dan atap lengkung bergaya kolonial menyimpan memori kejayaan perdagangan abad ke-19.\n\nNamun, modernisasi dan komersialisasi pariwisata membawa dilema tersendiri. Beberapa bangunan bersejarah dialihfungsikan menjadi kafe kekinian, sementara yang lain dibiarkan melapuk tergerus cuaca.\n\nEsai ini merefleksikan pentingnya menjaga keseimbangan antara konservasi cagar budaya dan tuntutan ekonomi modern.\n\nSemarang tidak boleh hanya menjual nostalgia, melainkan harus menghormati identitas sejarah di setiap bata tuanya.', 'Sutan Alamsyah', '8 Juni 2025', '15.8K', 'img/badminton_court.png', '[\"Semarang\",\"Sejarah\",\"Esai\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('24', 'Ekonomi', 'ekonomi', 'ekonomi', 'Energi Panas Bumi: Menggali Potensi Geothermal Indonesia yang Belum Optimal', 'Dengan 40% cadangan panas bumi dunia, Indonesia baru memanfaatkan sebagian kecil. Apa saja hambatan investasinya?', 'Ekonomi — Indonesia memegang predikat sebagai pemilik cadangan energi panas bumi (geothermal) terbesar di dunia, mencakup sekitar 40% dari total global. Namun, tingkat pemanfaatannya saat ini baru mencapai kurang dari 10%.\n\nHambatan utama dalam pengembangan geothermal adalah tingginya biaya investasi awal untuk eksplorasi dan rumitnya proses perizinan karena mayoritas cadangan berada di kawasan hutan lindung.\n\nAnalisis ekonomi menunjukkan bahwa transisi dari batu bara ke panas bumi dapat memangkas emisi karbon nasional secara signifikan.\n\nPemerintah perlu memberikan insentif fiskal yang lebih menarik bagi investor swasta agar harta karun hijau ini dapat menerangi nusantara.', 'Budi Santoso, ME', '7 Juni 2025', '24.1K', 'img/mandalika_motogp.png', '[\"Geothermal\",\"Energi\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('25', 'Berita Utama', 'berita', 'berita', 'Ilmuwan Indonesia Temukan Spesies Anggrek Langka Baru di Hutan Kalimantan', 'Spesies yang dinamai Dendrobium arianae ini memiliki kelopak berwarna ungu menyala dengan ketahanan cuaca ekstrem.', 'Kalimantan — Tim peneliti botani gabungan berhasil menemukan spesies anggrek langka baru di pedalaman hutan lindung Kalimantan Barat. Spesies ini diklasifikasikan ke dalam genus Dendrobium dan diberi nama Dendrobium arianae.\n\nAnggrek ini memiliki ciri khas yang sangat unik, yaitu kelopak berwarna ungu neon menyala dan kemampuan hidup menempel pada pohon tinggi tanpa air selama berminggu-minggu.\n\n\"Penemuan ini membuktikan bahwa kekayaan hayati hutan hujan Kalimantan masih menyimpan banyak misteri yang belum terkuak,\" kata ketua tim ekspedisi.\n\nUpaya konservasi darurat kini sedang diajukan agar habitat asli anggrek langka ini terlindungi dari pembalakan liar.', 'Flora Desk', '6 Juni 2025', '37.5K', 'img/anggrek_ungu.png', '[\"Anggrek\",\"Kalimantan\",\"Sains\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('26', 'Berita Utama', 'berita', 'berita', 'Jonatan Christie Juara All England 2026, Ukir Sejarah Tunggal Putra', 'Kemenangan dua game langsung atas wakil Denmark mengakhiri penantian panjang 10 tahun gelar tunggal putra All England.', 'Birmingham — Pebulutangkis tunggal putra Indonesia, Jonatan Christie, sukses merebut gelar juara turnamen prestisius All England 2026 setelah menundukkan rival sengitnya di babak final.\n\nDalam pertandingan yang berlangsung intens selama 48 menit, Jonatan mengendalikan tempo permainan dengan smash keras dan pertahanan rapat.\n\n\"Ini adalah impian masa kecil saya yang menjadi kenyataan. Terima kasih kepada seluruh rakyat Indonesia atas dukungannya,\" ujarnya penuh haru.\n\nGelar ini memperpanjang dominasi bulutangkis Indonesia di kancah internasional.', 'Slamet Rahardjo', '5 Juni 2025', '72.4K', 'img/badminton_court.png', '[\"Bulutangkis\",\"AllEngland\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('27', 'Berita Utama', 'berita', 'berita', 'Sirkuit Mandalika Siap Gelar MotoGP 2025, Logistik Pembalap Mulai Tiba', 'Penyelenggara mengonfirmasi kesiapan aspal sirkuit, marshal, dan akomodasi untuk menampung 100 ribu penonton.', 'Lombok Tengah — Logistik untuk gelaran MotoGP seri Indonesia di Sirkuit Mandalika dilaporkan mulai tiba melalui Bandara Internasional Lombok. Kontainer kargo yang membawa motor balap dan peralatan tim terlihat mulai memadati area paddock sirkuit.\n\nDirektur Utama MGPA menegaskan bahwa seluruh infrastruktur sirkuit termasuk pengaspalan ulang area run-off telah rampung 100%.\n\n\"Kami siap menyuguhkan balapan terbaik dunia dengan keindahan panorama alam Lombok,\" tuturnya.\n\nTiket menonton untuk hari balapan dikabarkan telah terjual habis.', 'Aditya Putra', '4 Juni 2025', '58.9K', 'img/mandalika_motogp.png', '[\"MotoGP\",\"Mandalika\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('28', 'Berita Utama', 'berita', 'berita', 'Lari Maraton Internasional Borobudur Diikuti 5.000 Pelari dari 20 Negara', 'Rute maraton melewati keindahan candi bersejarah Borobudur dan pedesaan asri sekitarnya.', 'Magelang — Borobudur Marathon 2025 sukses digelar pagi ini dengan diikuti oleh ribuan pelari dari dalam dan luar negeri. Rute lari tahun ini dirancang melewati jalan-jalan desa yang asri di sekitar kompleks Candi Borobudur, menyajikan pemandangan sawah dan pegunungan Menoreh.\n\nPelari asal Kenya mendominasi podium kategori Full Marathon putra dengan catatan waktu 2 jam 12 menit.\n\n\"Masyarakat desa sangat ramah, mereka berdiri di pinggir jalan menyemangati kami sepanjang rute,\" kata salah satu pelari internasional.\n\nAcara ini diharapkan mendongkrak pariwisata olahraga (sports tourism) di Jawa Tengah.', 'Eko Wahyudi', '3 Juni 2025', '31.2K', 'img/maraton_borobudur.png', '[\"Maraton\",\"Borobudur\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('29', 'Berita Utama', 'berita', 'berita', 'Indonesia Targetkan 5 Medali Emas di Olimpiade Musim Panas Mendatang', 'KONI dan Kemenpora fokus mematangkan persiapan atlet cabang panahan, angkat besi, dan bulutangkis.', 'Jakarta — Komite Olahraga Nasional Indonesia (KONI) bersama Kementerian Pemuda dan Olahraga (Kemenpora) menetapkan target realistis berupa 5 medali emas pada ajang Olimpiade Musim Panas mendatang.\n\nFokus pembinaan intensif saat ini diarahkan pada cabang-cabang andalan tradisional yang terbukti menyumbang medali di ajang sebelumnya.\n\n\"Pemusatan latihan nasional (Pelatnas) berjalan sangat ketat. Atlet-atlet kami sedang dalam kondisi fisik prima,\" ungkap ketua umum KONI.\n\nUji tanding internasional akan dilakukan di Eropa bulan depan.', 'Sport Desk', '2 Juni 2025', '43.5K', 'img/rupiah_exchange.png', '[\"Olimpiade\",\"Kemenpora\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('30', 'Opini', 'opini', 'opini', 'Paradoks Transportasi Publik: Mewah di Pusat, Terlantar di Pinggiran', 'Menganalisis ketimpangan integrasi moda transportasi massal antara kawasan elit Jakarta dan kota-kota satelit.', 'Jakarta — Sistem transportasi massal perkotaan seperti MRT dan LRT telah membawa wajah baru yang modern bagi pusat ibu kota Jakarta. Namun, jika kita melihat sedikit ke arah pinggiran atau kota-kota satelit seperti Depok, Bekasi, dan Bogor, pemandangannya sangat kontras.\n\nKeterbatasan halte feeder, jadwal angkutan yang tidak menentu, serta buruknya trotoar penunjang membuat warga pinggiran tetap bergantung pada kendaraan pribadi.\n\n\"Integrasi harus dilakukan secara merata dari hulu ke hilir. Jangan hanya menata daerah Sudirman-Thamrin,\" ujar seorang pengamat tata kota.\n\nKetimpangan ini harus segera diatasi agar target pengurangan polusi udara Jakarta dapat tercapai.', 'Rian Hidayat, MT', '1 Juni 2025', '19.3K', 'img/ai_startup.png', '[\"Transportasi\",\"Keadilan\",\"Opini\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('31', 'Hikmah', 'hikmah', 'hikmah', 'Merawat Ingatan Kolektif: Menelusuri Aksara Kuno Lontar Bali', 'Esai tentang upaya anak muda melestarikan manuskrip daun lontar kuno di tengah gempuran budaya digital serba instan.', 'Denpasar — Di era di mana informasi berpindah dalam hitungan milidetik dan disimpan di komputasi awan, sekelompok anak muda di Bali memilih jalan sunyi untuk merawat lembaran daun lontar tua.\n\nLontar-lontar ini bukan sekadar naskah kuno berdebu. Di dalam goresan aksara Bali di atas permukaan daun palem kering tersebut, tersimpan catatan pengobatan tradisional (usadha), filsafat hidup, astronomi, hingga tata cara bermasyarakat.\n\n\"Membaca lontar adalah cara kami berdialog langsung dengan leluhur,\" kata I Putu Suardika, salah satu inisiator gerakan digitalisasi lontar.\n\nUpaya ini membuktikan bahwa budaya kuno tidak harus mati karena modernitas, melainkan bisa hidup berdampingan melalui bantuan teknologi digital.', 'Putu Gede', '30 Mei 2025', '14.2K', 'img/timnas_football.png', '[\"Budaya\",\"Bali\",\"Lontar\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('32', 'Berita Utama', 'berita', 'berita', 'Perang Chip Global: Perebutan Dominasi Semikonduktor AS-Taiwan-China', 'Bagaimana pasokan komponen mikro chip menentukan kedaulatan teknologi dan arah industri otomotif dunia.', 'Taipei — Semikonduktor telah menjadi minyak bumi baru di era digital. Perebutan kontrol atas rantai pasok chip canggih kini melibatkan persaingan geopolitik sengit antara negara-negara adidaya dunia.\n\nTaiwan, melalui perusahaan raksasa TSMC, memegang kunci utama karena memproduksi lebih dari 60% semikonduktor dunia dan 90% chip berteknologi paling canggih.\n\n\"Siapa yang menguasai pasokan silikon, dialah yang mengendalikan masa depan kecerdasan buatan dan kekuatan militer global,\" tulis sebuah laporan strategis.\n\nUpaya AS membangun pabrik chip dalam negeri sedang dipacu untuk meminimalisir ketergantungan pasokan dari kawasan Selat Taiwan yang rawan konflik.', 'Tech Analyst', '29 Mei 2025', '48.1K', 'img/demokrasi_digital.png', '[\"Chip\",\"Geopolitik\",\"Sains\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('33', 'Berita Utama', 'berita', 'berita', 'Pemerintah Umumkan Pembangunan Jalur Kereta Api Cepat Tahap Dua', 'Proyek kereta cepat Jakarta-Surabaya resmi dimulai dengan rute melewati Bandung, Yogyakarta, dan Solo.', 'Jakarta — Kementerian Perhubungan secara resmi mengumumkan peta jalan pembangunan proyek Kereta Cepat Jakarta-Surabaya yang merupakan kelanjutan dari proyek Whoosh tahap pertama.\n\nProyek infrastruktur raksasa ini ditargetkan rampung pada tahun 2030 dan akan memangkas waktu tempuh perjalanan darat Jakarta-Surabaya menjadi hanya 3,5 jam saja.\n\n\"Ini adalah lompatan besar bagi konektivitas transportasi antar kota di Pulau Jawa,\" jelas Menteri Perhubungan dalam pemaparan di DPR.\n\nStudi kelayakan dan pembebasan lahan koridor Bandung-Yogyakarta akan dimulai pada kuartal ketiga tahun ini.', 'Humas Kemenhub', '28 Mei 2025', '65.4K', 'img/maraton_borobudur.png', '[\"KeretaCepat\",\"Kemenhub\",\"Nasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('34', 'Berita Utama', 'berita', 'berita', 'Suku Bunga Acuan BI Naik 25 Bps Menjadi 6.25% Demi Tekan Inflasi', 'Langkah BI merespon kebijakan suku bunga The Fed AS dan menjaga stabilitas nilai tukar Rupiah.', 'Jakarta — Rapat Dewan Gubernur (RDG) Bank Indonesia memutuskan untuk menaikkan suku bunga acuan BI-Rate sebesar 25 basis poin menjadi 6.25%.\n\nGubernur BI menyatakan kenaikan ini diperlukan untuk memitigasi risiko inflasi barang impor (imported inflation) akibat depresiasi nilai tukar rupiah terhadap dolar AS serta mengantisipasi penundaan penurunan bunga The Fed.\n\n\"Fokus kebijakan moneter BI tetap diarahkan pada penguatan stabilitas nilai tukar rupiah dan memastikan inflasi berada di sasaran 2.5% plus minus 1%,\" terangnya.\n\nPasar merespon positif keputusan ini dengan penguatan indeks saham gabungan.', 'Monetary Analyst', '27 Mei 2025', '39.0K', 'img/senja_desa.png', '[\"SukuBunga\",\"BI\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('35', 'Berita Utama', 'berita', 'berita', 'Kota Cerdas Nusantara: Implementasi IoT untuk Pemantauan Polusi Air', 'Sistem sensor real-time dipasang di sepanjang sungai utama ibu kota baru untuk menjaga kualitas air baku.', 'Nusantara — Otorita Ibu Kota Nusantara (IKN) berkolaborasi dengan lembaga riset teknologi nasional mulai memasang ratusan sensor Internet of Things (IoT) di sepanjang aliran sungai utama kawasan inti pusat pemerintahan.\n\nSensor-sensor ini mendeteksi kadar pH, oksigen terlarut, serta kandungan zat kimia berbahaya secara real-time dan mengirimkan datanya ke ruang pusat kontrol IKN.\n\n\"Ini memastikan bahwa setiap polusi air yang terjadi akibat konstruksi atau limbah domestik dapat dideteksi dalam hitungan menit sebelum mencemari waduk air baku utama,\" kata juru bicara IKN.\n\nTeknologi ini merupakan bagian dari visi IKN sebagai kota hutan cerdas yang berkelanjutan.', 'Lab Lingkungan', '26 Mei 2025', '42.7K', 'img/iot_polusi_air.png', '[\"SmartCity\",\"IoT\",\"Lingkungan\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('36', 'Berita Utama', 'berita', 'berita', 'Pembangunan IKN Tahap Tiga Fokus Pada Kompleks Olahraga dan Seni', 'Pemerintah mengalokasikan dana APBN tambahan untuk infrastruktur sosial pendukung di Ibu Kota Nusantara.', 'Nusantara — Otorita Ibu Kota Nusantara (IKN) mengumumkan dimulainya proyek konstruksi tahap ketiga. Fase ini akan difokuskan penuh pada pembangunan kompleks sarana olahraga (sports center) berstandar internasional dan gedung pusat kesenian.\n\n\"IKN bukan hanya pusat administrasi pemerintahan, tapi juga rumah bagi kebudayaan dan gaya hidup sehat Indonesia,\" ujar kepala Otorita.\n\nFasilitas ini diharapkan rampung sebelum peringatan HUT RI mendatang.', 'Rina Wijaya', '25 Mei 2025', '24.8K', 'img/badminton_court.png', '[\"IKN\",\"Nasional\",\"Infrastruktur\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('37', 'Hikmah', 'hikmah', 'hikmah', 'Festival Budaya Nusantara di Candi Prambanan Tarik Ribuan Turis', 'Acara tahunan menampilkan tarian kolosal tradisional dari Aceh hingga Papua di bawah sorotan lampu candi.', 'Yogyakarta — Festival Budaya Nusantara resmi dibuka malam ini di pelataran Candi Prambanan. Ribuan penonton lokal dan wisatawan mancanegara memadati tribun terbuka untuk menyaksikan tarian kolosal.\n\nSebanyak 500 seniman tradisional dari berbagai pelosok negeri berpartisipasi dalam pentas bertema persatuan bangsa ini.\n\n\"Ini adalah momentum emas mempertemukan tradisi masa lalu dengan pariwisata masa kini,\" ungkap Gubernur DIY.', 'Eko Wahyudi', '24 Mei 2025', '32.5K', 'img/mandalika_motogp.png', '[\"Festival\",\"Prambanan\",\"Nasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('38', 'Berita Utama', 'berita', 'berita', 'Pemerintah Siapkan Mitigasi El Nino di Sektor Pertanian Padi', 'Kementerian Pertanian mempercepat program pompa air gratis dan asuransi gagal panen untuk 1 juta petani.', 'Jakarta — Kementerian Pertanian mengambil langkah preventif menghadapi ancaman kekeringan akibat fenomena iklim El Nino. Program penyaluran 50.000 unit mesin pompa air ke daerah sentra pangan mulai didistribusikan pekan ini.\n\nPemerintah juga memastikan dana asuransi tani siap dicairkan jika terjadi gagal panen di wilayah rawan puso.\n\n\"Langkah ini penting untuk mengamankan cadangan beras nasional,\" kata menteri.', 'Dian Pratiwi', '23 Mei 2025', '19.4K', 'img/maraton_borobudur.png', '[\"Pertanian\",\"ElNino\",\"Nasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('39', 'Berita Utama', 'berita', 'berita', 'Kemenkes Bagikan 1 Juta Alat Deteksi Stunting Gratis ke Puskesmas', 'Penyaluran antropometri kit digital terstandar diharapkan menurunkan angka tengkes secara signifikan.', 'Jakarta — Kementerian Kesehatan membagikan satu juta paket alat ukur antropometri digital terstandar ke puskesmas dan posyandu di daerah 3T. Langkah ini bertujuan melakukan deteksi dini kasus gizi buruk pada balita.\n\n\"Dengan alat ukur digital, data berat dan tinggi badan anak langsung terhubung ke database pusat secara real-time,\" jelas menteri.\n\nPemerintah menargetkan prevalensi stunting turun di bawah 14% tahun ini.', 'Indra Jaya', '22 Mei 2025', '22.1K', 'img/iot_polusi_air.png', '[\"Kesehatan\",\"Kemenkes\",\"Nasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('40', 'Berita Utama', 'berita', 'berita', 'Polri Luncurkan Sistem Tilang Elektronik ETLE Mobile Berbasis AI', 'Kamera terpasang di helm petugas mampu mengidentifikasi pengendara tanpa sabuk pengaman atau helm secara otomatis.', 'Jakarta — Korlantas Polri meresmikan sistem tilang elektronik terbaru berbasis kecerdasan buatan yang dinamakan ETLE Mobile. Kamera pintar yang dipasang di kendaraan patroli dan helm petugas akan mendeteksi pelanggaran secara otomatis saat berpatroli.\n\n\"Sistem AI akan menyaring plat nomor dan jenis pelanggaran secara presisi tanpa perlu menghentikan pengendara di jalan,\" jelas Kakorlantas.\n\nInovasi ini diharapkan meningkatkan kepatuhan lalu lintas secara masif.', 'Bambang Sutrisno', '21 Mei 2025', '51.2K', 'img/desa_wisata.png', '[\"LaluLintas\",\"Polri\",\"Nasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('41', 'Berita Utama', 'berita', 'berita', 'Eksplorasi Bulan: Misi Artemis Sukses Mendarat di Kutub Selatan Bulan', 'Pendarat berawak mengirimkan foto resolusi tinggi pertama kawah es yang berpotensi menjadi sumber air astronot.', 'Houston — Badan Antariksa Amerika Serikat (NASA) mengonfirmasi keberhasilan misi pendaratan berawak Artemis di wilayah Kutub Selatan Bulan. Pendarat sukses menyentuh permukaan kawah es yang selama ini belum pernah dijelajahi.\n\nAstronot dilaporkan kondisi tanah stabil dan mulai memasang alat bor sampel tanah.\n\n\"Ini langkah awal manusia membangun pangkalan permanen di luar bumi,\" kata direktur misi.', 'Global Desk', '20 Mei 2025', '62.8K', 'img/g20_summit.png', '[\"Antariksa\",\"NASA\",\"Sains\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('42', 'Berita Utama', 'berita', 'berita', 'Krisis Pangan Global: PBB Serukan Bantuan Darurat untuk Afrika Timur', 'Lebih dari 20 juta jiwa terancam kelaparan akibat kekeringan parah berkepanjangan dan konflik bersenjata.', 'Nairobi — Sekjen PBB menyampaikan seruan darurat kemanusiaan global untuk menggalang dana sebesar USD 4,5 militar guna mengatasi krisis pangan ekstrem di kawasan Tanduk Afrika.\n\nKekeringan selama empat musim berturut-turut dikombinasikan dengan harga pupuk yang melonjak tinggi memperburuk kelaparan.\n\n\"Dunia tidak boleh berpaling dari tragedi kemানুsiaan terbesar dekade ini,\" tegas juru bicara PBB.', 'Ahmad Rizki', '19 Mei 2025', '28.7K', 'img/rupiah_exchange.png', '[\"PBB\",\"Krisis\",\"Internasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('43', 'Berita Utama', 'berita', 'berita', 'KTT Asean ke-46: Fokus pada Konektivitas Ekonomi Regional', 'Para pemimpin negara menyepakati integrasi sistem pembayaran QR code lintas batas di seluruh Asia Tenggara.', 'Bangkok — Konferensi Tingkat Tinggi (KTT) ASEAN ke-46 resmi dimulai dengan fokus integrasi ekonomi digital regional. Seluruh kepala negara menyepakati perluasan QR Code Payment ASEAN agar turis dapat bertransaksi langsung tanpa tukar valuta.\n\n\"Ini adalah tonggak penting kemandirian ekonomi kawasan menghadapi ketidakpastian global,\" kata PM Thailand.', 'Rina Wijaya', '18 Mei 2025', '33.4K', 'img/ai_startup.png', '[\"ASEAN\",\"Ekonomi\",\"Internasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('44', 'Berita Utama', 'berita', 'berita', 'Ilmuwan Temukan Planet Baru Layak Huni Berjarak 20 Tahun Cahaya', 'Planet Gliese 581g dikonfirmasi memiliki suhu permukaan berkisar antara -10 hingga 30 derajat Celsius.', 'Jenewa — Tim astronom internasional mengumumkan penemuan planet ekstrasurya baru yang berada di zona layak huni bintangnya. Planet yang diberi kode nama Gliese 581g ini memiliki ukuran mirip bumi dengan gravitasi stabil.\n\n\"Atmosfer planet tersebut kemungkinan mengandung air cair, prasyarat utama adanya kehidupan,\" ungkap ketua peneliti.\n\nPenemuan ini memicu rencana misi pengamatan teleskop luar angkasa generasi terbaru.', 'Sains Desk', '17 Mei 2025', '45.7K', 'img/timnas_football.png', '[\"Sains\",\"Astronomi\",\"Internasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('45', 'Berita Utama', 'berita', 'berita', 'Perjanjian Iklim Paris Baru: 150 Negara Sepakat Turunkan Emisi', 'Deklarasi bersama menargetkan penghentian penggunaan PLTU batu bara secara global mulai tahun 2035.', 'Paris — Pertemuan Puncak Iklim COP30 menghasilkan kesepakatan bersejarah baru. Sebanyak 150 negara sepakat menandatangani adendum Perjanjian Paris untuk mempercepat target Net Zero Emission.\n\nNegara maju setuju menggandakan dana kompensasi transisi energi hijau bagi negara berkembang.\n\n\"Kita tidak punya banyak waktu lagi untuk menyelamatkan ekosistem bumi dari pemanasan global,\" ujar Sekjen PBB.', 'Global Desk', '16 Mei 2025', '37.2K', 'img/demokrasi_digital.png', '[\"Iklim\",\"Lingkungan\",\"Internasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('46', 'Berita Utama', 'berita', 'berita', 'Unjuk Rasa Perubahan Iklim Blokade Pusat Kota London Selama Dua Hari', 'Ribuan demonstran menuntut pemerintah Inggris menghentikan izin pengeboran minyak baru di Laut Utara.', 'London — Aksi unjuk rasa besar-besaran yang digelar koalisi aktivis lingkungan melumpuhkan kawasan pusat bisnis London. Demonstran memblokir jembatan utama dan jalan protokol dengan mendirikan tenda-tenda kemah.\n\nKepolisian setempat dilaporkan menahan ratusan pengunjuk rasa yang menolak dibubarkan.\n\n\"Kami akan terus bertahan hingga pemerintah membatalkan izin tambang fosil baru,\" kata juru bicara aksi.', 'Ahmad Rizki', '15 Mei 2025', '41.3K', 'img/pendidikan_sekolah.png', '[\"Demo\",\"Inggris\",\"Internasional\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('47', 'Berita Utama', 'berita', 'berita', 'Ekspor Nikel Indonesia Melonjak 35% di Semester Pertama 2025', 'Kebijakan hilirisasi nikel berhasil mendongkrak devisa negara dan menarik investasi baterai kendaraan listrik.', 'Jakarta — Badan Pusat Statistik (BPS) melaporkan nilai ekspor produk olahan nikel Indonesia mencapai rekor tertinggi baru dengan lonjakan 35% secara tahunan.\n\nInvestasi pada pabrik peleburan (smelter) baterai kendaraan listrik di Morowali dan Weda Bay menjadi motor utama kenaikan devisa.\n\n\"Hilirisasi terbukti memberikan nilai tambah berlipat ganda bagi ekonomi nasional,\" tegas Menteri Keuangan.', 'Dian Pratiwi', '14 Mei 2025', '39.6K', 'img/senja_desa.png', '[\"Nikel\",\"Hilirisasi\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('48', 'Berita Utama', 'berita', 'berita', 'Inflasi Juni Terkendali di Level 2.8%, BI Klaim Kebijakan Efektif', 'Stabilitas harga bahan pangan pokok menjadi faktor utama terjaganya inflasi di batas target pemerintah.', 'Jakarta — Indeks Harga Konsumen (IHK) nasional mencatatkan tingkat inflasi tahunan sebesar 2.8% pada bulan Juni kemarin, berada aman di kisaran target Bank Indonesia.\n\nDeputi Gubernur BI menyatakan sinergi pengendalian harga pangan daerah (TPID) sukses meredam lonjakan harga pasca hari raya.\n\n\"Suku bunga acuan saat ini cukup memadai untuk menjaga kestabilan moneter,\" terangnya.', 'Monetary Analyst', '13 Mei 2025', '27.1K', 'img/anggrek_ungu.png', '[\"Inflasi\",\"BI\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('49', 'Berita Utama', 'berita', 'berita', 'Nilai Transaksi Digital Banking Tembus Rp5.000 Triliun di Q1', 'Pergeseran gaya hidup nontunai di kota-kota besar Indonesia mempercepat penetrasi aplikasi mobile banking.', 'Jakarta — Bank Indonesia mencatat pertumbuhan luar biasa pada transaksi perbankan digital. Selama kuartal pertama tahun ini, total nilai transaksi perbankan elektronik menembus angka Rp5.000 triliun.\n\nPenggunaan QRIS yang meluas ke pedagang mikro dituding sebagai pemicu utama kebiasaan nontunai masyarakat.\n\n\"Fintech dan perbankan kini saling berkolaborasi melayani nasabah,\" ungkap Deputi BI.', 'Ratna Kartika, SE', '12 Mei 2025', '43.2K', 'img/badminton_court.png', '[\"QRIS\",\"Banking\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('50', 'Berita Utama', 'berita', 'berita', 'Pemerintah Berikan Insentif Pajak untuk Pembelian Mobil Listrik Baru', 'Diskon PPN hingga 10% bertujuan mempercepat adopsi kendaraan ramah lingkungan di Indonesia.', 'Jakarta — Pemerintah resmi memperpanjang kebijakan insentif Pajak Pertambahan Nilai Ditanggung Pemerintah (PPN DTP) untuk pembelian mobil listrik berbasis baterai yang diproduksi lokal.\n\nKebijakan ini diklaim berhasil memangkas harga jual mobil listrik hingga puluhan juta rupiah.\n\n\"Kami ingin menciptakan ekosistem industri hijau yang kompetitif di ASEAN,\" ujar Menteri Perindustrian.', 'Dian Pratiwi', '11 Mei 2025', '34.5K', 'img/mandalika_motogp.png', '[\"MobilListrik\",\"Pajak\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('51', 'Berita Utama', 'berita', 'berita', 'Harga Emas Antam Tembus Rekor Baru Rp1.550.000 Per Gram', 'Ketidakpastian geopolitik global memicu investor memindahkan aset ke safe haven logam mulia.', 'Jakarta — Harga emas batangan produksi PT Aneka Tambang Tbk (Antam) kembali melonjak tajam ke level Rp1.550.000 per gram. Ini merupakan harga tertinggi sepanjang sejarah.\n\nAnalis menyebut fluktuasi nilai tukar rupiah dan ketegangan politik Timur Tengah memaksa pasar melakukan aksi lindung nilai (hedging) menggunakan emas.\n\n\"Emas tetap menjadi pilihan investasi paling aman saat krisis,\" kata perwakilan Antam.', 'Monetary Analyst', '10 Mei 2025', '58.1K', 'img/maraton_borobudur.png', '[\"Emas\",\"Antam\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('52', 'Berita Utama', 'berita', 'berita', 'Kunjungan Wisatawan Asing ke Bali Meningkat Pesat Pasca Pandemi', 'Pembukaan rute penerbangan langsung baru dari Tiongkok dan India menyumbang lonjakan okupansi hotel.', 'Denpasar — Dinas Pariwisata Provinsi Bali mencatat jumlah kunjungan wisatawan mancanegara mendekati angka 6 juta orang dalam setahun terakhir. Rata-rata lama tinggal wisman dilaporkan naik menjadi 8 hari.\n\nKawasan Ubud, Kuta, dan Uluwatu terpantau ramai padat turis.\n\n\"Kami fokus pada pariwisata berkualitas yang menjaga kelestarian budaya lokal Bali,\" jelas kepala Dinas.', 'Rina Wijaya', '9 Mei 2025', '46.4K', 'img/iot_polusi_air.png', '[\"Pariwisata\",\"Bali\",\"Ekonomi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('53', 'Berita Utama', 'berita', 'berita', 'Keamanan Siber: Ransomware Baru Serang Sistem Perbankan Global', 'Lembaga sandi negara menghimbau seluruh perbankan nasional memperbarui enkripsi keamanan database.', 'Jakarta — Badan Siber dan Sandi Negara (BSSN) mengeluarkan peringatan dini terkait munculnya varian virus ransomware baru yang menargetkan server lembaga keuangan utama di seluruh dunia.\n\nModus operandi peretas adalah mengenkripsi data nasabah lalu meminta tebusan cryptocurrency puluhan juta dolar.\n\n\"Pihak perbankan diminta melakukan backup dingin harian secara ketat,\" imbau direktur siber.', 'Tech Desk', '8 Mei 2025', '55.3K', 'img/desa_wisata.png', '[\"Siber\",\"Ransomware\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('54', 'Berita Utama', 'berita', 'berita', 'Kacamata Pintar AR Terbaru Google Mulai Diproduksi Massal', 'Perangkat dilengkapi asisten AI real-time mampu menerjemahkan percakapan asing langsung ke layar lensa.', 'California — Google mengumumkan dimulainya lini produksi massal untuk kacamata pintar berteknologi Augmented Reality (AR) generasi kedua. Perangkat yang berbobot hanya 75 gram ini dirancang mirip kacamata biasa.\n\n\"Integrasi dengan AI Gemini memungkinkan pengguna menanyakan benda yang mereka lihat di jalanan,\" kata eksekutif Google.\n\nPerangkat ini diproyeksikan mulai dipasarkan secara global awal tahun depan.', 'Fajar Nugroho', '7 Mei 2025', '61.4K', 'img/g20_summit.png', '[\"Google\",\"AR\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('55', 'Berita Utama', 'berita', 'berita', 'Pembangkit Listrik Tenaga Surya Terapung Terbesar Mulai Beroperasi', 'Pemasangan 200 ribu panel surya di atas waduk mampu menyuplai energi bersih untuk 50 ribu rumah.', 'Cirebon — Proyek Pembangkit Listrik Tenaga Surya (PLTS) Terapung berkapasitas 145 MW resmi beroperasi penuh hari ini. Panel-panel fotovoltaik membentang menutupi 60% luas waduk penampung air.\n\nSelain menghasilkan listrik bersih, panel apung ini juga mengurangi penguapan air waduk secara drastis.\n\n\"Ini adalah model transisi energi bersih yang ideal bagi wilayah pulau kecil Indonesia,\" jelas menteri ESDM.', 'Tech Desk', '6 Mei 2025', '39.7K', 'img/rupiah_exchange.png', '[\"PLTS\",\"EnergiHijau\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('56', 'Berita Utama', 'berita', 'berita', 'Mobil Otonom Resmi Diizinkan Beroperasi di Jalan Protokol Jakarta', 'Uji coba terbatas angkutan kota tanpa supir mulai diterapkan di rute khusus Sudirman-Thamrin.', 'Jakarta — Pemerintah Provinsi DKI Jakarta memberikan izin uji coba operasional bagi taksi otonom (self-driving car) di rute khusus halte Sudirman. Mobil ini dilengkapi 12 kamera dan sensor Lidar.\n\n\"Selama uji coba, supir cadangan manusia tetap duduk di kursi kemudi untuk mengantisipasi keadaan darurat,\" kata Dishub.\n\nJika dinilai aman, armada otonom akan diperbanyak di jalur busway.', 'Fajar Nugroho', '5 Mei 2025', '48.9K', 'img/ai_startup.png', '[\"MobilOtonom\",\"Jakarta\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('57', 'Berita Utama', 'berita', 'berita', 'Teknologi Pertanian Pintar: Petani Hidroponik Gunakan AI untuk Nutrisi', 'Sensor otomatis mengukur kelembaban, suhu air, dan kadar nutrisi guna menghasilkan sayuran kualitas ekspor.', 'Bandung — Komunitas petani hidroponik milenial di Lembang menerapkan sistem kecerdasan buatan untuk mengelola kebun selada skala besar. Algoritma AI menganalisis kebutuhan nutrisi tanaman berdasarkan cuaca.\n\n\"Produktivitas panen kami meningkat 40% dan pemborosan air terpangkas hingga setengahnya,\" aku ketua kelompok tani.\n\nHasil panen selada kini telah menembus pasar supermarket Singapura.', 'Tech Desk', '4 Mei 2025', '32.8K', 'img/timnas_football.png', '[\"Pertanian\",\"IoT\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('58', 'Berita Utama', 'berita', 'berita', 'Piala Dunia FIFA: Timnas Garuda Masuk Grup Neraka Kualifikasi Putaran 3', 'Indonesia akan bersaing dengan Jepang, Australia, dan Arab Saudi memperebutkan tiket ke AS.', 'Jakarta — Hasil drawing babak kualifikasi Piala Dunia FIFA menempatkan Timnas Indonesia di Grup C bersama negara-negara raksasa sepak bola Asia.\n\nKetua PSSI meminta publik tidak pesimis dan mengajak seluruh masyarakat memberikan dukungan penuh di stadion.\n\n\"Kami akan berjuang hingga menit akhir demi mimpi melihat Garuda terbang di Piala Dunia,\" tegas kapten timnas.', 'Bambang Sutrisno', '3 Mei 2025', '95.6K', 'img/demokrasi_digital.png', '[\"Timnas\",\"PialaDunia\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('59', 'Berita Utama', 'berita', 'berita', 'Kejuaraan Bulutangkis Indonesia Open Resmi Digelar di Istora Senayan', 'Atlet top dari 30 negara bertarung memperebutkan total hadiah uang tunai sebesar USD 1,3 juta.', 'Jakarta — Turnamen bulutangkis Indonesia Open Super 1000 resmi dibuka hari ini di Istora Senayan. Ribuan pendukung fanatik tanah air terlihat memadati tribune dengan atribut merah putih sejak pagi hari.\n\nSektor ganda putra Indonesia diunggulkan meraih medali emas pada gelaran bergengsi edisi tahun ini.\n\n\"Atmosfer penonton Istora selalu menjadi yang terbaik di dunia,\" aku pebulutangkis nomor satu asal Denmark.', 'Slamet Rahardjo', '2 Mei 2025', '67.2K', 'img/pendidikan_sekolah.png', '[\"Bulutangkis\",\"Istora\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('60', 'Berita Utama', 'berita', 'berita', 'Pembalap F1 Indonesia Perdana Raih Poin di GP Monaco', 'Keberhasilan finis di peringkat ke-8 mencatatkan namanya dalam sejarah otomotif nasional.', 'Monaco — Sirkuit jalan raya Monaco yang sempit menjadi saksi sejarah bagi dunia olahraga otomotif Indonesia. Pembalap debutan tanah air sukses finis di posisi ke-8 dan berhak meraih 4 poin klasemen F1.\n\nStrategi pemilihan ban basah saat hujan deras di tengah balapan menjadi kunci sukses menyalip para rival senior.\n\n\"Kemenangan ini saya persembahkan untuk seluruh fans di tanah air,\" ungkapnya bangga.', 'Aditya Putra', '1 Mei 2025', '78.3K', 'img/senja_desa.png', '[\"Formula1\",\"GPMonaco\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('61', 'Berita Utama', 'berita', 'berita', 'Proliga 2025: Jakarta Lavani Pertahankan Gelar Juara Berturut-turut', 'Kemenangan mutlak 3-0 atas Surabaya Samator mengukuhkan dominasi tim di liga voli nasional.', 'Yogyakarta — Tim voli putra Jakarta Lavani berhasil keluar sebagai juara Proliga setelah menundukkan Surabaya Samator di laga Grand Final yang mendebarkan di GOR Among Raga.\n\nBlock kokoh dan servis tajam dari spiker asing Lavani menjadi momok pertahanan Samator.\n\n\"Ini hasil kerja keras seluruh tim selama pemusatan latihan intensif,\" kata pelatih Lavani.', 'Sport Desk', '30 April 2025', '45.8K', 'img/anggrek_ungu.png', '[\"Proliga\",\"Voli\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('62', 'Berita Utama', 'berita', 'berita', 'Tim Panahan Indonesia Raih Emas di Kejuaraan Asia Bangkok', 'Akurasi tembakan tim beregu campuran sukses menundukkan dominasi tim unggulan Korea Selatan.', 'Bangkok — Tim panahan beregu campuran Indonesia sukses mempersembahkan medali emas pada Kejuaraan Panahan Asia di Thailand. Mereka mengalahkan tim Korea Selatan dengan skor tipis di babak penentuan.\n\n\"Ketenangan mental atlet di bawah cuaca panas ekstrim menjadi kunci utama akurasi tembakan panah kami,\" puji kepala pelatih.\n\nPrestasi ini menjadi modal penting menuju tiket kualifikasi Olimpiade.', 'Sport Desk', '29 April 2025', '33.4K', 'img/badminton_court.png', '[\"Panahan\",\"Emas\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('63', 'Opini', 'opini', 'opini', 'Etika AI: Siapkah Hukum Indonesia Menghadapi Deepfake?', 'Penyebaran video manipulasi wajah berbasis kecerdasan buatan mulai mengancam privasi dan stabilitas politik.', 'Opini — Teknologi kecerdasan buatan telah melahirkan deepfake, sebuah inovasi manipulasi video yang sangat mulus dan sulit dibedakan dari kenyataan oleh mata telanjang.\n\nHukum positif Indonesia melalui UU ITE saat ini dinilai belum spesifik mengatur delik pemalsuan identitas digital menggunakan AI.\n\nKita butuh regulasi komprehensif yang tidak hanya menghukum pelaku, tetapi juga mewajibkan platform media sosial menyertakan metadata pelabelan konten hasil rekayasa kecerdasan buatan.', 'Prof. Dr. Maya Sari', '28 April 2025', '24.2K', 'img/mandalika_motogp.png', '[\"Hukum\",\"AI\",\"Opini\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('64', 'Opini', 'opini', 'opini', 'Urgensi Transportasi Publik untuk Mengatasi Polusi Udara Kota', 'Mengapa membangun flyover baru bukan solusi mengatasi kemacetan dan kabut asap perkotaan Indonesia.', 'Opini — Menambah panjang jalan raya untuk mengurai kemacetan adalah sebuah paradoks (induce demand). Semakin lebar jalan, semakin banyak pula kendaraan pribadi yang memadatinya.\n\nSolusi mutlak polusi udara kota-kota besar di Indonesia bukanlah memperluas jalan, melainkan membangun infrastruktur transportasi massal terintegrasi yang murah, aman, dan tepat waktu.\n\nPemerintah harus berani mengambil kebijakan tidak populer demi masa depan udara bersih anak cucu kita.', 'Rian Hidayat, MT', '27 April 2025', '19.7K', 'img/maraton_borobudur.png', '[\"Transportasi\",\"Lingkungan\",\"Opini\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('65', 'Opini', 'opini', 'opini', 'Ekonomi Hijau: Antara Komitmen Global dan Realita Lapangan', 'Dilema negara berkembang dalam menyeimbangkan target transisi energi bersih dengan pertumbuhan industri lokal.', 'Opini — Kampanye internasional untuk menghentikan pemakaian bahan bakar fosil kerap mengabaikan fakta bahwa jutaan rakyat negara berkembang masih menggantungkan hidupnya pada sektor tambang murah.\n\nTransisi menuju ekonomi hijau harus dilakukan secara adil (just transition) dengan menyiapkan lapangan kerja pengganti terlebih dahulu.\n\nNegara-negara maju wajib merealisasikan janji dana bantuan iklim, bukan sekedar memberikan sanksi dagang karbon.', 'Ratna Kartika, SE', '26 April 2025', '15.6K', 'img/iot_polusi_air.png', '[\"Ekonomi\",\"Iklim\",\"Opini\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('66', 'Pendidikan', 'pendidikan', 'pendidikan', 'Pendidikan Vokasi: Kunci Menghadapi Bonus Demografi 2030', 'Menghubungkan kurikulum sekolah kejuruan dengan kebutuhan nyata industri masa depan.', 'Opini — Melimpahnya jumlah penduduk usia produktif pada tahun 2030 (bonus demografi) bisa menjadi berkah sekaligus bencana bagi Indonesia jika tidak dikelola dengan benar.\n\nKurikulum pendidikan vokasi saat ini harus segera dirombak total agar melahirkan lulusan siap kerja di sektor ekonomi kreatif dan teknologi informasi.\n\nSinergi link and match antara sekolah dengan industri bukan lagi sekedar slogan, melainkan keharusan mutlak.', 'Dr. Hendra Wijaya', '25 April 2025', '21.3K', 'img/desa_wisata.png', '[\"Pendidikan\",\"Vokasi\",\"Opini\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('67', 'Essay', 'essay', 'essay', 'Menyusuri Jejak Sunyi di Lereng Merapi: Catatan Tentang Ketabahan', 'Esai naratif tentang kehidupan masyarakat desa terpencil pasca erupisi hebat gunung berapi.', 'Merapi — Debu vulkanik putih masih menyelimuti sisa-sisa pohon pinus yang hangus. Namun di sela-sela bebatuan vulkanik yang dingin, tunas hijau mulai menyembul kembali.\n\nEsai ini menceritakan tentang ketabahan luar biasa para penduduk desa lereng Merapi. Mereka menolak menyerah pada takdir alam.\n\nMereka membangun kembali rumah mereka dengan material yang dimuntahkan gunung, hidup bersanding mesra dengan ancaman bencana yang sewaktu-waktu bisa datang kembali mengetuk pintu rumah.', 'Saraswati Dewi', '24 April 2025', '18.2K', 'img/g20_summit.png', '[\"Merapi\",\"Bencana\",\"Essay\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('68', 'Essay', 'essay', 'essay', 'Rumah Tanpa Dinding: Refleksi Tentang Keterbukaan Era Digital', 'Esai filosofis tentang hilangnya batas wilayah privat manusia akibat paparan sosial media berlebih.', 'Essay — Dahulu, rumah adalah benteng perlindungan di mana segala hal yang terjadi di dalamnya tertutup rapat dari mata dunia luar.\n\nKini di era internet, kita secara sukarela meruntuhkan dinding-dinding privasi tersebut melalui unggahan cerita harian. Setiap sudut kamar, piring sarapan, hingga tangisan duka dipamerkan demi perhatian digital.\n\nRefleksi ini mempertanyakan kembali: apakah kita masih memiliki diri kita seutuhnya, atau telah menjadi pertunjukan abadi bagi orang asing?', 'Arian Ramadhan', '23 April 2025', '15.4K', 'img/rupiah_exchange.png', '[\"Refleksi\",\"Sosmed\",\"Essay\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('69', 'Essay', 'essay', 'essay', 'Secangkir Teh di Pagi Hari: Menemukan Kembali Keheningan Jiwa', 'Catatan ringan tentang ritual sederhana menghela napas di tengah hiruk-pikuk gaya hidup urban modern.', 'Essay — Di pagi hari yang sibuk di Jakarta, klakson kendaraan bersahutan dan jadwal kereta cepat memburu waktu. Saya memutuskan berhenti sejenak dan menyeduh daun teh melati.\n\nMelihat kepulan uap hangat dan menghirup aroma tanah basah mengingatkan saya akan esensi hidup yang sering terlupakan.\n\nBahwa kebahagiaan bukan tentang seberapa cepat kita berlari mengejar karir, melainkan kemampuan merasakan eksistensi diri pada detik ini.', 'Saraswati Dewi', '22 April 2025', '22.1K', 'img/ai_startup.png', '[\"GayaHidup\",\"Nostalgia\",\"Essay\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('70', 'Essay', 'essay', 'essay', 'Seni Menunggu di Stasiun Kereta: Menghargai Waktu yang Hilang', 'Esai tentang perjumpaan-perjumpaan sekilas para komuter perkotaan dan fragmen cerita kehidupan mereka.', 'Essay — Stasiun Manggarai pukul 5 sore adalah rimba manusia. Ribuan tubuh berdesakan menunggu kedatangan kereta listrik komuter arah Bogor.\n\nDi balik wajah-wajah lelah yang menatap layar ponsel, saya membaca ragam cerita: perjuangan ayah demi susu anak, impian mahasiswa baru, hingga kerinduan ibu paruh baya.\n\nMenunggu di stasiun bukan lagi waktu kosong yang terbuang, melainkan galeri kehidupan manusia urban yang paling jujur.', 'Sutan Alamsyah', '21 April 2025', '19.8K', 'img/timnas_football.png', '[\"Stasiun\",\"Komuter\",\"Essay\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('71', 'Essay', 'essay', 'essay', 'Membaca Hujan: Dialog Antara Air, Tanah, dan Ingatan Masa Kecil', 'Nostalgia tentang aroma tanah basah petrichor dan kenangan bermain air hujan tanpa beban.', 'Essay — Hujan sore ini turun dengan ketukan ritmis di atas atap seng kontrakan saya. Seketika aroma petrikor menguar, membawa ingatan saya melompat ke masa dua puluh tahun lalu.\n\nMasa di mana hujan adalah undangan pesta bermain bola di lapangan becek desa, tanpa ketakutan masuk angin atau cucian basah.\n\nHujan hari ini mengajarkan saya tentang kesederhanaan rasa syukur anak kecil yang hilang tergerus usia dewasa.', 'Agus Prasetyo', '20 April 2025', '14.9K', 'img/demokrasi_digital.png', '[\"Hujan\",\"Nostalgia\",\"Essay\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('72', 'Hikmah', 'hikmah', 'hikmah', 'Sejarah Perkembangan Aksara Nusantara: Dari Pallawa Hingga Carakan', 'Artikel edukasi menelusuri akar tulisan kuno Indonesia yang menjadi identitas sastra kerajaan masa lalu.', 'Artikel — Jauh sebelum aksara Latin digunakan secara nasional, bangsa Indonesia telah memiliki kekayaan aksara daerah yang sangat tinggi.\n\nBerakar dari aksara Pallawa asal India Selatan, para pujangga nusantara memodifikasinya menjadi aksara Kawi, Jawa (Hanacaraka), Sunda kuno, Lontara Bugis, hingga aksara Batak.\n\nArtikel ini mengulas bagaimana goresan pena bambu di atas daun lontar dan kulit kayu menjadi sarana penyebaran ilmu pengetahuan masa kerajaan dahulu.', 'Historian Team', '19 April 2025', '31.2K', 'img/pendidikan_sekolah.png', '[\"Aksara\",\"Sejarah\",\"Budaya\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('73', 'Pendidikan', 'pendidikan', 'pendidikan', 'Manfaat Meditasi Untuk Kesehatan Mental di Era Distraksi Digital', 'Panduan praktis melatih fokus dan menurunkan kadar stres akibat paparan layar gawai yang intens.', 'Artikel — Otak manusia modern menerima informasi dalam sehari setara dengan konsumsi informasi manusia abad pertengahan selama seumur hidup. Akibatnya, kita rentan mengalami kelelahan mental.\n\nStudi medis membuktikan bahwa latihan meditasi pernapasan (mindfulness) selama 10 menit sehari terbukti mereduksi hormon kortisol penanda stres.\n\nArtikel ini memberikan panduan langkah demi langkah mempraktikkan relaksasi di sela jam kerja.', 'Dr. Lestari Nugraha', '18 April 2025', '44.3K', 'img/senja_desa.png', '[\"Kesehatan\",\"Mental\",\"Meditasi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('74', 'Hikmah', 'hikmah', 'hikmah', 'Arkeologi Bawah Air: Mensingkap Bangkai Kapal Kuno di Selat Karimata', 'Ekspedisi gabungan berhasil mengamankan ribuan keramik dinasti Song dari dasar laut sedalaman 30 meter.', 'Sains — Selat Karimata merupakan jalur sutra laut perdagangan kuno yang menyimpan banyak misteri. Penyelam arkeologi nasional berhasil menemukan sisa-sisa lambung kapal kargo kayu adat ke-12.\n\nDi dalam reruntuhan kapal tersebut, ditemukan kendi tembikar, koin tembaga, dan piring porselen utuh yang memiliki nilai sejarah tidak ternilai.\n\nUpaya pengangkatan dan restorasi cagar budaya ini sedang dipersiapkan di museum nasional.', 'Sains Desk', '17 April 2025', '35.6K', 'img/anggrek_ungu.png', '[\"Arkeologi\",\"Sejarah\",\"Laut\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('75', 'Hikmah', 'hikmah', 'hikmah', 'Seni Tenun Ikat NTT: Simbol Status Sosial dan Nilai Filosofis', 'Setiap goresan motif tenunan menyimpan doa, cerita suku, dan penanda kelas adat pemakainya.', 'Artikel — Tenun ikat di Nusa Tenggara Timur bukan sekedar selembar kain penutup tubuh. Proses pembuatannya yang memakan waktu berbulan-bulan menggunakan pewarna alami dari akar mengkudu dan daun nila.\n\nSetiap suku di Alor, Flores, hingga Sumba memiliki motif khusus yang menceritakan silsilah keluarga dan relasi kosmik manusia dengan alam.\n\nKarya seni bernilai seni tinggi ini kini mulai dipasarkan ke butik mode kelas atas eropa.', 'Historian Team', '16 April 2025', '38.2K', 'img/badminton_court.png', '[\"Tenun\",\"NTT\",\"Budaya\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('76', 'Hikmah', 'hikmah', 'hikmah', 'Kearifan Subak Bali: Harmoni Antara Manusia, Alam, dan Tri Hita Karana', 'Bagaimana sistem irigasi tradisional Bali bertahan melintasi zaman sebagai warisan budaya dunia UNESCO.', 'Bali — Subak bukan sekadar urusan membagi air sawah. Di balik jaringan parit dan bendungan kecil di lereng-lereng gunung Bali, terdapat filosofi hidup Tri Hita Karana: keselarasan hubungan manusia dengan Tuhan, sesama, dan alam sekitar.\n\nDalam artikel ini, kami menelusuri bagaimana organisasi petani adat mengelola sumber daya air secara demokratis dan adil sejak abad ke-9.', 'Wayan Suantara', '15 April 2025', '29.4K', 'img/mandalika_motogp.png', '[\"Budaya\",\"Bali\",\"Sejarah\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('77', 'Pendidikan', 'pendidikan', 'pendidikan', 'Menumbuhkan Minat Baca Anak di Era Digital: Tantangan Literasi Abad 21', 'Strategi jitu para pendidik dan orang tua mendampingi anak menyaring distraksi layar gadget.', 'Pendidikan — Gawai pintar menawarkan sejuta kemudahan, namun di sisi lain mengikis rentang konsentrasi anak-anak kita. Buku fisik kini harus bersaing ketat dengan video durasi pendek yang candu.\n\nPeneliti literasi menyarankan pembatasan screen-time dan penciptaan pojok baca keluarga sebagai langkah awal membangun kebiasaan membaca sejak dini.', 'Dewi Lestari', '14 April 2025', '34.2K', 'img/maraton_borobudur.png', '[\"Pendidikan\",\"Mental\",\"Keluarga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('78', 'Ekonomi', 'ekonomi', 'ekonomi', 'Kebangkitan Ekonomi Kreatif Syariah di Kalangan Kreator Muda Indonesia', 'Bagaimana modest fashion dan kuliner halal menjadi motor baru ekosistem startup lokal.', 'Ekonomi — Generasi muda muslim Indonesia kini tidak lagi sekadar menjadi konsumen industri halal global. Mereka mulai membangun brand modest fashion premium, produk kecantikan ramah lingkungan, serta teknologi finansial syariah.\n\nDukungan ekosistem digital mempercepat penetrasi pasar hingga ke Timur Tengah dan Eropa.', 'Zulkifli Hasan', '13 April 2025', '26.8K', 'img/iot_polusi_air.png', '[\"Ekonomi\",\"Startup\",\"Bisnis\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('79', 'Pendidikan', 'pendidikan', 'pendidikan', 'Pembinaan Atlet Usia Dini: Kunci Emas Menembus Panggung Olimpiade', 'Evaluasi pembibitan atlet berbakat di daerah dan pentingnya sports science.', 'Olahraga — Sukses prestasi olahraga di kancah internasional tidak lahir secara instan. Diperlukan pencarian bakat yang terstruktur sejak usia sekolah dasar, didukung nutrisi memadai dan metodologi sport science terbaru.\n\nNegara tetangga telah menerapkan sport science secara masif, dan Indonesia harus segera mengejar ketertinggalan.', 'Budi Sudarsono', '12 April 2025', '32.5K', 'img/desa_wisata.png', '[\"Olahraga\",\"Pendidikan\",\"Kesehatan\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('80', 'Essay', 'essay', 'essay', 'Suara Angin Malam di Perbatasan: Catatan Tentang Jarak dan Jiwa', 'Esai naratif tentang kehidupan sunyi para penjaga mercusuar di pulau terluar nusantara.', 'Essay — Di ujung utara pulau terluar, mercusuar berdiri tegak menantang badai. Bagi para penjaga malam di sana, kesunyian bukanlah musuh, melainkan teman karib yang setia.\n\nDalam esai ini, saya merefleksikan arti jarak dan pengorbanan demi keselamatan kapal-kapal asing yang melintas tanpa pernah tahu nama penjaga lampu penuntun mereka.', 'Arian Ramadhan', '11 April 2025', '19.3K', 'img/g20_summit.png', '[\"Essay\",\"Sastra\",\"Refleksi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('81', 'Pendidikan', 'pendidikan', 'pendidikan', 'Pentingnya Etika Bermedia Sosial Sejak Bangku Sekolah Menengah', 'Mengapa kecerdasan digital harus berjalan beriringan dengan sopan santun komunikasi virtual.', 'Opini — Perundungan siber (cyberbullying) dan penyebaran berita palsu di kalangan remaja kian mencemaskan. Kurikulum sekolah saat ini tidak boleh hanya fokus pada kemahiran coding atau mengoperasikan software, tetapi wajib menyisipkan pelajaran empati digital.\n\nAnak didik harus diajarkan bahwa di balik setiap akun medsos, ada manusia nyata yang memiliki perasaan.', 'Maya Sari', '10 April 2025', '22.7K', 'img/rupiah_exchange.png', '[\"Opini\",\"Pendidikan\",\"Sosmed\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('82', 'Hikmah', 'hikmah', 'hikmah', 'Tradisi Sekaten Yogyakarta: Akulturasi Budaya dan Dakwah yang Lestari', 'Menelusuri sejarah perayaan Maulid Nabi melalui perpaduan gamelan pusaka dan syiar Islam.', 'Artikel — Alunan gamelan Kyai Guntur Madu bergema di halaman Masjid Gede Kauman, menandai dimulainya perayaan Sekaten. Tradisi berusia ratusan tahun warisan Kesultanan Mataram ini merupakan salah satu contoh terbaik harmonisasi budaya lokal Jawa dengan nilai luhur ajaran Islam.\n\nMari menilik kembali nilai-nilai toleransi dan persatuan di balik gemuruh pasar malam sekaten.', 'Historian Team', '9 April 2025', '28.1K', 'img/ai_startup.png', '[\"Budaya\",\"Sejarah\",\"Religi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('83', 'Pendidikan', 'pendidikan', 'pendidikan', 'Metode Pendidikan STEM: Mempersiapkan Kreator Masa Depan', 'Mengapa integrasi Sains, Teknologi, Teknik, dan Matematika krusial bagi generasi emas.', 'Pendidikan — Industri masa depan menuntut keahlian analitis dan pemecahan masalah yang kompleks. Melalui pendekatan STEM (Science, Technology, Engineering, Math), siswa diajak bereksperimen langsung memecahkan problem nyata di lingkungan mereka.\n\nBelajar tidak lagi sekadar menghafal rumus di papan tulis, melainkan mempraktikkannya untuk menciptakan inovasi baru.', 'Hendra Wijaya', '8 April 2025', '37.6K', 'img/timnas_football.png', '[\"Pendidikan\",\"Sains\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('84', 'Ekonomi', 'ekonomi', 'ekonomi', 'Transisi Kendaraan Listrik di Indonesia: Menjawab Keraguan Konsumen', 'Ulasan mendalam mengenai kesiapan infrastruktur SPKLU dan ketahanan baterai di iklim tropis.', 'Ekonomi — Minat masyarakat terhadap mobil listrik (EV) terus tumbuh seiring munculnya model-model murah. Namun, keraguan akan jarak tempuh baterai dan ketersediaan stasiun pengisian daya (SPKLU) di luar kota besar masih membayangi.\n\nPemerintah dan pihak swasta perlu mempercepat pembangunan SPKLU jalur mudik guna mempercepat ekosistem transportasi hijau.', 'Dian Pratiwi', '7 April 2025', '31.9K', 'img/demokrasi_digital.png', '[\"Ekonomi\",\"Lingkungan\",\"Teknologi\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('85', 'Hikmah', 'hikmah', 'hikmah', 'Pemerintah Resmikan Museum Sejarah Seni Rupa Terbesar di Kota Solo', 'Museum memuat ribuan lukisan klasik dan modern karya maestro nusantara.', 'Solo — Presiden meresmikan Museum Seni Rupa Raden Saleh di Kota Surakarta. Kompleks museum senilai Rp400 militar ini menyimpan koleksi mahakarya maestro pelukis legendaris sejak era kolonial hingga seni rupa kontemporer.\n\nMuseum diharapkan menjadi ikon edukasi budaya baru bagi generasi muda dan mendongkrak pariwisata seni Jawa Tengah.', 'Indra Jaya', '6 April 2025', '41.2K', 'img/pendidikan_sekolah.png', '[\"Pemerintah\",\"Budaya\",\"Sejarah\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('86', 'Olahraga', 'olahraga', 'olahraga', 'Revolusi Bulutangkis Indonesia: Kunci Regenerasi Atlet Sektor Putri', 'Evaluasi pembinaan jangka panjang di pelatnas untuk mengembalikan kejayaan sektor tunggal putri.', 'Cipayung — Persatuan Bulutangkis Seluruh Indonesia (PBSI) tengah menggencarkan program regenerasi intensif bagi atlet tunggal putri. Penggunaan sport science untuk mengukur ketahanan fisik serta evaluasi psikologis berkala menjadi pilar utama reformasi kurikulum latihan.\n\n\"Kami menargetkan dalam dua tahun mendatang tunggal putri Indonesia kembali merajai podium dunia,\" ujar legenda bulutangkis nasional.', 'Liem Swie King', '5 April 2025', '34.5K', 'img/senja_desa.png', '[\"Bulutangkis\",\"Pelatnas\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('87', 'Olahraga', 'olahraga', 'olahraga', 'Sirkuit Mandalika Dorong Kebangkitan Talenta Balap Motor Lokal', 'Ajang internasional MotoGP terbukti mempercepat pembinaan bakat pembalap muda di wilayah timur.', 'Lombok — Gelaran balap motor tingkat dunia di Sirkuit Mandalika tidak hanya menjadi ajang pariwisata. Keberadaan sirkuit berstandar internasional ini dimanfaatkan Kemenpora bersama IMI untuk menyelenggarakan akademi balap bagi pemuda lokal.\n\nBeberapa talenta asal NTB kini mulai menembus kejuaraan asia tingkat junior.', 'Aditya Putra', '4 April 2025', '48.2K', 'img/anggrek_ungu.png', '[\"Mandalika\",\"MotoGP\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('88', 'Olahraga', 'olahraga', 'olahraga', 'Angkat Besi Konsisten Sumbang Medali Emas di Kancah Dunia', 'Bagaimana fasilitas latihan terpusat melahirkan lifter tangguh kelas dunia secara berkesinambungan.', 'Jakarta — Cabang olahraga angkat besi kembali membuktikan kedigdayaannya. Lifter muda Indonesia berhasil membawa pulang dua medali emas dari kejuaraan dunia di Tashkent.\n\nKunci sukses angkat besi nasional terletak pada disiplin tinggi, fasilitas latihan terpusat, dan pemantauan nutrisi yang sangat ketat.', 'Slamet Rahardjo', '3 April 2025', '29.8K', 'img/badminton_court.png', '[\"AngkatBesi\",\"Emas\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('89', 'Olahraga', 'olahraga', 'olahraga', 'Manfaat Latihan Kardio Teratur bagi Kesehatan Jantung Lansia', 'Studi klinis membuktikan jalan cepat dan bersepeda santai menurunkan risiko stroke secara signifikan.', 'Bandung — Kesehatan fisik di usia senja dapat dijaga melalui aktivitas fisik yang terukur. Dokter spesialis jantung menyarankan lansia melakukan olahraga kardio ringan seperti jalan cepat atau bersepeda santai selama 150 menit per minggu.\n\nOlahraga teratur terbukti menjaga elastisitas pembuluh darah dan menstabilkan tekanan darah.', 'Dr. Lestari Nugraha', '2 April 2025', '31.2K', 'img/mandalika_motogp.png', '[\"Kesehatan\",\"Lansia\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('90', 'Olahraga', 'olahraga', 'olahraga', 'PSSI Rancang Kurikulum Sepak Bola Nasional Berbasis Big Data', 'Integrasi data statistik performa pemain muda untuk mempermudah pemantauan bakat timnas.', 'Jakarta — PSSI meluncurkan sistem pangkalan data statistik digital untuk seluruh liga usia muda di Indonesia. Melalui teknologi sensor GPS dan analisis video berbasis kecerdasan buatan, performa fisik dan taktis setiap pemain dapat terpantau secara langsung oleh tim pencari bakat timnas.\n\n\"Ini era baru pencarian bakat sepak bola nasional,\" ungkap ketua umum.', 'Indra Jaya', '1 April 2025', '52.3K', 'img/maraton_borobudur.png', '[\"SepakBola\",\"PSSI\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('91', 'Olahraga', 'olahraga', 'olahraga', 'Kejuaraan Tenis Meja Nasional Sukses Jaring Ratusan Atlet Pelajar', 'Turnamen kelompok umur di GOR Ragunan melahirkan harapan baru tenis meja tanah air.', 'Jakarta — GOR Ragunan dipadati ratusan atlet tenis meja tingkat pelajar dari 34 provinsi. Turnamen ini dirancang khusus untuk menjaring atlet muda potensial yang akan diproyeksikan masuk ke Pusat Pendidikan dan Latihan Mahasiswa (PPLM).\n\nTaktik permainan cepat dan spin tajam mendominasi partai final tunggal putra.', 'Sport Desk', '31 Maret 2025', '22.6K', 'img/iot_polusi_air.png', '[\"TenisMeja\",\"Pelajar\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('92', 'Olahraga', 'olahraga', 'olahraga', 'Gaya Hidup Sehat: Tren Bersepeda Komunitas Urban Pasca Pandemi', 'Menjelajah kota dan menjalin pertemanan baru melalui kampanye ramah lingkungan bersepeda.', 'Surabaya — Tren bersepeda masih tetap populer di kota-kota besar Indonesia. Komunitas sepeda perkotaan rutin mengadakan kegiatan gowes bersama setiap akhir pekan, menyusuri jalan protokol sembari mengampanyekan pengurangan emisi karbon.\n\nSelain menyehatkan tubuh, bersepeda menjadi sarana rekreasi sosial yang menyegarkan pikiran.', 'Rian Hidayat', '30 Maret 2025', '38.1K', 'img/desa_wisata.png', '[\"Bersepeda\",\"GayaHidup\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('93', 'Olahraga', 'olahraga', 'olahraga', 'Indonesia Siap Selenggarakan Kejuaraan Dunia Panjat Tebing 2026', 'Kesiapan fasilitas dinding panjat internasional di Jakarta terus dikebut pengerjaannya.', 'Jakarta — Federasi Panjat Tebing Indonesia (FPTI) menyatakan kesiapannya menjadi tuan rumah Kejuaraan Dunia IFSC Climbing World Cup 2026. Keberhasilan atlet speed Indonesia meraih medali emas olimpiade menjadi magnet utama ketertarikan dunia internasional.\n\nDinding panjat baru berstandar olimpiade kini sedang dibangun di kawasan Senayan.', 'Sport Desk', '29 Maret 2025', '27.4K', 'img/g20_summit.png', '[\"PanjatTebing\",\"Kejuaraan\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('94', 'Olahraga', 'olahraga', 'olahraga', 'Pentingnya Metode Pemulihan Otot bagi Atlet Guna Mencegah Cedera', 'Sains olahraga menekankan pentingnya ice bath, fisioterapi, dan tidur cukup bagi atlet.', 'Makassar — Performa puncak atlet tidak hanya ditentukan oleh porsi latihan yang berat. Aspek pemulihan (*recovery*) pasca latihan memegang peranan yang sama pentingnya untuk mencegah risiko cedera kronis.\n\nPenggunaan terapi ice bath dingin, pijat fisioterapi terapis bersertifikat, serta pola tidur minimal 8 jam menjadi protokol wajib di tim-tim olahraga profesional.', 'Dr. Hendra Wijaya', '28 Maret 2025', '33.6K', 'img/rupiah_exchange.png', '[\"Kesehatan\",\"Sains\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('95', 'Olahraga', 'olahraga', 'olahraga', 'Perkembangan Pesat Industri E-Sports Jadi Cabang Olahraga Prestasi', 'Bagaimana game kompetitif bertransformasi dari sekedar hobi menjadi karir menjanjikan.', 'Jakarta — E-Sports kini telah resmi diakui sebagai cabang olahraga prestasi di Indonesia. Atlet-atlet game profesional tanah air menorehkan prestasi gemilang di tingkat internasional dengan membawa pulang piala kejuaraan dunia mobile gaming.\n\nArtikel ini membahas disiplin latihan fisik dan mental yang dijalani atlet e-sports profesional.', 'Dian Pratiwi', '27 Maret 2025', '41.8K', 'img/ai_startup.png', '[\"ESports\",\"Gaming\",\"Olahraga\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('96', 'Foto', 'foto', 'foto', 'Foto Jurnal: Wajah-wajah Ketabahan Nelayan Tradisional Indonesia', 'Rekaman lensa merekam kerasnya perjuangan nelayan mencari nafkah di bawah ombak besar pantai selatan.', 'Pantai Selatan — Di tengah deburan ombak besar pantai selatan, jurnalis foto kami mengabadikan perjuangan nelayan tradisional mendorong perahu kayu mereka menerjang ombak.\n\nFoto-foto ini berkisah tentang ketabahan, keringat, dan cinta keluarga yang terangkum dalam raut wajah legam terbakar sinar matahari.', 'Rian Hidayat, MP', '26 Maret 2025', '18.5K', 'img/timnas_football.png', '[\"Foto\",\"Nelayan\",\"Sosial\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('97', 'Foto', 'foto', 'foto', 'Foto Jurnal: Keindahan Pagi Hari Selimut Kabut Kaki Gunung Rinjani', 'Lukisan alam dari balik lensa menangkap momen matahari terbit di atas Danau Segara Anak.', 'Lombok — Gunung Rinjani memancarkan pesona magisnya di pagi hari. Bidikan kamera menangkap momen dramatis kabut tipis turun menyelimuti Danau Segara Anak saat sinar matahari keemasan mulai menembus sela-sela tebing.\n\nKeindahan lanskap ini menjadi bukti agungnya alam Indonesia.', 'Sutan Alamsyah', '25 Maret 2025', '24.2K', 'img/demokrasi_digital.png', '[\"Foto\",\"Rinjani\",\"Wisata\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('98', 'Hikmah', 'hikmah', 'hikmah', 'Foto Jurnal: Gemerlap Warna Pasar Malam Tradisional di Pelosok Desa', 'Kombinasi cahaya lampu neon sederhana dan kegembiraan anak-anak menaiki wahana permainan rakyat.', 'Banyumas — Jauh dari gemerlap mall kota besar, pasar malam tradisional tetap menjadi primadona hiburan warga desa. Lensa kamera kami mengabadikan pendar lampu hias bianglala kayu, asap harum harum manis merah muda, serta senyum tawa anak-anak.\n\nSebuah romantisme kebersamaan yang bersahaja.', 'Agus Prasetyo', '24 Maret 2025', '19.7K', 'img/pendidikan_sekolah.png', '[\"Foto\",\"PasarMalam\",\"Budaya\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('99', 'Foto', 'foto', 'foto', 'Foto Jurnal: Potret Semangat Belajar Siswa Sekolah Tapal Batas', 'Meski fasilitas minim, pancaran mata penuh mimpi anak-anak perbatasan tetap menyala.', 'Kalimantan Barat — Di sebuah ruang kelas beralas tanah dan berdinding bambu di dekat perbatasan Indonesia-Malaysia, jurnalis foto kami menangkap momen-momen emosional.\n\nAnak-anak belajar membaca dengan satu buku bersama. Sorot mata mereka penuh binar mimpi menjadi pembangun masa depan negeri.', 'Dewi Lestari', '23 Maret 2025', '29.1K', 'img/senja_desa.png', '[\"Foto\",\"Sekolah\",\"Perbatasan\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('100', 'Foto', 'foto', 'foto', 'Foto Jurnal: Kemeriahan Akulturasi Budaya Grebeg Sudiro di Solo', 'Bidikan lensa merekam keindahan lampion merah bersanding gunungan onde-onde adat Jawa.', 'Solo — Perayaan Grebeg Sudiro menghadirkan wajah persatuan yang sangat indah di kawasan Pasar Gede Surakarta. Kamera menangkap potret kerukunan warga etnis Tionghoa dan Jawa berbaur berebut gunungan buah dan kue keranjang di bawah lampion barongsai.\n\nSimbol harmoni kebhinekaan nusantara.', 'Historian Team', '22 Maret 2025', '21.4K', 'img/anggrek_ungu.png', '[\"Foto\",\"Solo\",\"Festival\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('101', 'Foto', 'foto', 'foto', 'Foto Jurnal: Aksi Bersih-bersih Pantai Bali Bersama Relawan Lingkungan', 'Potret kerja nyata ratusan pasang tangan menyelamatkan habitat laut dari sampah plastik.', 'Bali — Jurnalis foto kami mengikuti aksi ratusan relawan lokal dan mancanegara memunguti sampah plastik di sepanjang garis Pantai Kuta.\n\nVisual deretan karung sampah, keringat relawan, serta senja jingga yang mulai bersih menyuarakan pesan penting pelestarian alam bagi keberlanjutan bumi kita.', 'Ratna Kartika', '21 Maret 2025', '32.8K', 'img/badminton_court.png', '[\"Foto\",\"Bali\",\"Lingkungan\"]', 'published', '2026-09-07 07:35:01', '2026-09-07 07:35:01'),
('103', 'Berita Utama', 'berita', 'berita', 'Peluncuran Satelit Komunikasi Nusantara Tiga Sukses Meluncur ke Orbit', 'Satelit komunikasi tercanggih berkapasitas 300 Gbps sukses mengorbit untuk memperluas akses internet di seluruh pelosok nusantara.', 'Jakarta — Badan Riset dan Inovasi Nasional (BRIN) bersama konsorsium telekomunikasi nasional resmi meluncurkan Satelit Nusantara Tiga ke orbit geostasioner dini hari tadi.\n\nPeluncuran roket pengangkut berlangsung mulus tanpa kendala teknis dari fasilitas antariksa internasional.\n\nSatelit ini memiliki kapasitas transmisi data sebesar 300 Gbps yang dirancang untuk memperluas akses internet pita lebar kecepatan tinggi hingga ke pulau-pulau terluar dan daerah terpencil di seluruh Indonesia.\n\n\"Ini adalah momentum bersejarah kedaulatan digital bangsa menuju era Indonesia Emas 2045,\" ujar Menkominfo dalam sambutannya.', 'Redaksi Teknologi', '7 September 2026', '8.5K', 'img/ai_startup.png', '[\"Satelit\",\"Teknologi\",\"Nasional\"]', 'published', '2026-09-07 07:47:54', '2026-09-07 07:47:54');

DROP TABLE IF EXISTS `ads`;
CREATE TABLE `ads` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `type` enum('manual','google') DEFAULT 'manual',
  `slot` varchar(100) NOT NULL,
  `content` text,
  `google_client` varchar(200) DEFAULT NULL,
  `google_slot` varchar(100) DEFAULT NULL,
  `url` varchar(500) DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',
  `image` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `ads` (`id`, `name`, `type`, `slot`, `content`, `google_client`, `google_slot`, `url`, `active`, `image`, `created_at`) VALUES
('1', 'GreenLife Insurance — Leaderboard', 'manual', 'leaderboard', '', NULL, NULL, 'https://example.com/greenlife', '1', 'img/desa_wisata.png', '2026-09-07 07:35:01'),
('2', 'AriTel 5G — Native Feed', 'manual', 'native1', '', NULL, NULL, 'https://example.com/aritel', '1', 'img/ai_startup.png', '2026-09-07 07:35:01'),
('3', 'Kopi Nusantara — Native Sidebar', 'manual', 'native2', '', NULL, NULL, 'https://example.com/kopi', '1', 'img/timnas_football.png', '2026-09-07 07:35:01'),
('4', 'Google Ads — Rectangle 300x250', 'google', 'google_rectangle', '', 'ca-pub-XXXXXXXXXXXXXXXX', '1234567890', '', '1', NULL, '2026-09-07 07:35:01'),
('5', 'Google Ads — Sticky Bottom', 'google', 'google_sticky', '', 'ca-pub-XXXXXXXXXXXXXXXX', '0987654321', '', '1', NULL, '2026-09-07 07:35:01');

DROP TABLE IF EXISTS `comments`;
CREATE TABLE `comments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `article_id` int NOT NULL,
  `name` varchar(150) NOT NULL,
  `comment` text NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `article_id` (`article_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `comments` (`id`, `article_id`, `name`, `comment`, `created_at`) VALUES
('1', '1', 'Ahmad Fauzi', 'Pembahasan yang sangat mendalam dan berbobot. Senang membaca ulasan di Pucuk Pena.', '2026-09-07 08:35:01'),
('2', '1', 'Siti Rahma', 'Setuju sekali. Sangat relevan dengan kondisi lapangan saat ini.', '2026-09-07 09:35:01');


DROP TABLE IF EXISTS `breaking_news`;
CREATE TABLE `breaking_news` (
  `id` int NOT NULL AUTO_INCREMENT,
  `text` varchar(500) NOT NULL,
  `active` tinyint(1) DEFAULT '1',
  `sort_order` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `breaking_news` (`id`, `text`, `active`, `sort_order`, `created_at`) VALUES
('1', 'BREAKING: Pemerintah Umumkan Kebijakan Energi Terbarukan Baru', '1', '1', '2026-09-07 07:35:01'),
('2', 'TERKINI: Timnas Indonesia Menang di Kualifikasi Piala Asia', '1', '2', '2026-09-07 07:35:01'),
('3', 'UPDATE: Deklarasi Bersama Ekonomi Digital ASEAN Disahkan', '1', '3', '2026-09-07 07:35:01'),
('4', 'INFO: Program Beasiswa Nasional 2025 Dibuka untuk Mahasiswa', '1', '4', '2026-09-07 07:35:01');

SET FOREIGN_KEY_CHECKS=1;
